# Generated by Django 4.0.4 on 2022-06-21 14:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 21, 14, 56, 40, 385053, tzinfo=utc), null=True),
        ),
    ]
