# Generated by Django 4.0.4 on 2022-06-22 19:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='logo',
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 22, 19, 58, 52, 835017, tzinfo=utc), null=True),
        ),
    ]
