# Generated by Django 4.0.4 on 2022-06-23 15:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_campaign_logo_campaign_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='bots',
            name='campaign_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.campaign'),
        ),
        migrations.AddField(
            model_name='bots',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responses',
            name='bot_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.bots'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 23, 15, 35, 52, 31660, tzinfo=utc), null=True),
        ),
    ]
